export const getAllContactConstans = {
  GET_ALL_CONTACT_REQUEST: "GET_ALL_CONTACT_REQUEST",
  GET_ALL_CONTACT_SUCCESS: "GET_ALL_CONTACT_SUCCESS",
  GET_ALL_CONTACT_FAIL: "GET_ALL_CONTACT_FAIL",
};

export const createContactConstans = {
  CREATE_CONTACT_REQUEST: "CREATE_CONTACT_REQUEST",
  CREATE_CONTACT_SUCCESS: "CREATE_CONTACT_SUCCESS",
  CREATE_CONTACT_FAIL: "CREATE_CONTACT_FAIL",
};

export const updateContactConstans = {
  UPDATE_CONTACT_REQUEST: "UPDATE_CONTACT_REQUEST",
  UPDATE_CONTACT_SUCCESS: "UPDATE_CONTACT_SUCCESS",
  UPDATE_CONTACT_FAIL: "UPDATE_CONTACT_FAIL",
};

export const deleteContactConstans = {
  DELET_CONTACT_REQUEST: "DELET_CONTACT_REQUEST",
  DELET_CONTACT_SUCCESS: "DELET_CONTACT_SUCCESS",
  DELET_CONTACT_FAIL: "DELET_CONTACT_FAIL",
};
